services:
  iot-consumer:
    build: .
    env_file:
      - .env
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    networks:
      - liwaisi-shared-network
    restart: unless-stopped
#create a shared network before this file execution
networks:
  liwaisi-shared-network:
    external: true