services:
  iot-consumer:
    build: .
    env_file:
      - .env
    networks:
      - liwaisi-shared-network
    restart: unless-stopped
#create a shared network before this file execution
networks:
  liwaisi-shared-network:
    external: true