// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// APIRestPorts is an autogenerated mock type for the APIRestPorts type
type APIRestPorts struct {
	mock.Mock
}

// RunServer provides a mock function with given fields:
func (_m *APIRestPorts) RunServer() {
	_m.Called()
}

// NewAPIRestPorts creates a new instance of APIRestPorts. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAPIRestPorts(t interface {
	mock.TestingT
	Cleanup(func())
}) *APIRestPorts {
	mock := &APIRestPorts{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
