// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	entities "github.com/liwaisi-tech/iot-mqtt-tem-subscriber/internal/domain/entities/climate_data"
	mock "github.com/stretchr/testify/mock"
)

// ClimateDataServicePorts is an autogenerated mock type for the ClimateDataServicePorts type
type ClimateDataServicePorts struct {
	mock.Mock
}

// GetLatestClimateData provides a mock function with given fields:
func (_m *ClimateDataServicePorts) GetLatestClimateData() (*entities.ClimateDataEntity, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLatestClimateData")
	}

	var r0 *entities.ClimateDataEntity
	var r1 error
	if rf, ok := ret.Get(0).(func() (*entities.ClimateDataEntity, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *entities.ClimateDataEntity); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ClimateDataEntity)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClimateDataServicePorts creates a new instance of ClimateDataServicePorts. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClimateDataServicePorts(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClimateDataServicePorts {
	mock := &ClimateDataServicePorts{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
