// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/liwaisi-tech/iot-mqtt-tem-subscriber/internal/domain/entities/climate_data"
	mock "github.com/stretchr/testify/mock"
)

// ClimateDataRepositoryPort is an autogenerated mock type for the ClimateDataRepositoryPort type
type ClimateDataRepositoryPort struct {
	mock.Mock
}

// CreateClimateData provides a mock function with given fields: ctx, entity
func (_m *ClimateDataRepositoryPort) CreateClimateData(ctx context.Context, entity *entities.ClimateDataEntity) (string, error) {
	ret := _m.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for CreateClimateData")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.ClimateDataEntity) (string, error)); ok {
		return rf(ctx, entity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.ClimateDataEntity) string); ok {
		r0 = rf(ctx, entity)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.ClimateDataEntity) error); ok {
		r1 = rf(ctx, entity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClimateDataRepositoryPort creates a new instance of ClimateDataRepositoryPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClimateDataRepositoryPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClimateDataRepositoryPort {
	mock := &ClimateDataRepositoryPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
