// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/liwaisi-tech/iot-mqtt-tem-subscriber/internal/domain/entities/climate_data"
	mock "github.com/stretchr/testify/mock"
)

// GetLatestClimateDataUseCasePort is an autogenerated mock type for the GetLatestClimateDataUseCasePort type
type GetLatestClimateDataUseCasePort struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx
func (_m *GetLatestClimateDataUseCasePort) Execute(ctx context.Context) (*entities.ClimateDataEntity, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *entities.ClimateDataEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*entities.ClimateDataEntity, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *entities.ClimateDataEntity); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ClimateDataEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGetLatestClimateDataUseCasePort creates a new instance of GetLatestClimateDataUseCasePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetLatestClimateDataUseCasePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetLatestClimateDataUseCasePort {
	mock := &GetLatestClimateDataUseCasePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
