// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MQTTPorts is an autogenerated mock type for the MQTTPorts type
type MQTTPorts struct {
	mock.Mock
}

// RunConsumer provides a mock function with given fields: topic
func (_m *MQTTPorts) RunConsumer(topic string) {
	_m.Called(topic)
}

// NewMQTTPorts creates a new instance of MQTTPorts. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMQTTPorts(t interface {
	mock.TestingT
	Cleanup(func())
}) *MQTTPorts {
	mock := &MQTTPorts{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
