// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// SaveClimateDataUseCasePort is an autogenerated mock type for the SaveClimateDataUseCasePort type
type SaveClimateDataUseCasePort struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, eventMessage
func (_m *SaveClimateDataUseCasePort) Execute(ctx context.Context, eventMessage []byte) error {
	ret := _m.Called(ctx, eventMessage)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = rf(ctx, eventMessage)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSaveClimateDataUseCasePort creates a new instance of SaveClimateDataUseCasePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSaveClimateDataUseCasePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *SaveClimateDataUseCasePort {
	mock := &SaveClimateDataUseCasePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
